### ISSUE TITLE
Final Project Recheck

### ISSUE THREAD

**Issue by safesit23** [sit-2021-int214/004-movie-industry#6]
น้องลืมใส่
- Link Power BI + Analytical Inferential Statistics  ใน README ของ REPO ครับ

**Comment by tsongglod123** [comment]
ถ้าพี่หมายถึง README ในหน้า Main repo 
เดี๋ยวเพิ่มเติมให้ครับ

**Comment by tsongglod123** [comment]
- [ ] Add Link to Power BI
- [ ] Add Link to Analytical Inferential Statistics folder
- [ ] Update Main README

**Comment by tsongglod123** [comment]
- [ ] Pending review
@safesit23

**Comment by tsongglod123** [comment]
> น้องลืมใส่
> 
> * Link Power BI + Analytical Inferential Statistics  ใน README ของ REPO ครับ

test

**Comment by tsongglod123** [comment]
> น้องลืมใส่
> 
> * Link Power BI + Analytical Inferential Statistics  ใน README ของ REPO ครับ

[Main README](https://github.com/sit-2021-int214/004-movie-industry/blob/main/README.md) (Primary README in this repository)
- [x] Add Link to Power BI
- [x] Add Link to Analytical Inferential Statistics folder
- [x] Update README (add new topics & minor update)

**Comment by tsongglod123** [comment]
For @safesit23 
- [x] Review
- [x] Approve
